---
kind: Service
apiVersion: v1
metadata:
  name: angos
  namespace: angos
  labels:
    app.kubernetes.io/name: angos
spec:
  selector:
    app.kubernetes.io/name: angos
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
