---
apiVersion: v1
kind: Service
metadata:
  name: angos
  namespace: angos
  labels:
    app: angos
spec:
  type: ClusterIP
  selector:
    app: angos
  ports:
    - name: http
      port: 8000
      targetPort: http
